baseURL = "/"
languageCode = "en-us"
title = "Wookets Wove"
theme = "kube"
description = "blue v blue"
Paginate = 25
pygmentsUseClasses=true
[Params]
  RSSLink = "/index.xml"
  author = "wookets" # add your company name
  github = "wookets" # add your github profile name
  twitter = "wookets" # add your twitter profile
  email = "wookets@gmail.com"

[[menu.main]]
    name = "Software"
    weight = -100
    url = "/software/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
[[menu.main]]
    name = "Writing"
    weight = -100
    url = "/writing/"
